Fix #6: Added HandMesh
evonove/vr-experience pull request #10
Opened 2019-12-11 11:19 UTC by ilariacuccaro

Fix #6 
Hand's CollisionShape generates Warning, because CollisionShape should be used as a child of Area, RigidBody, StaicBody... However, the game starts.

2019-12-11 13:44 UTC, Girbons requested changes

2019-12-11 13:44 UTC, Girbons commented on Player.tscn
> +[node name="RightHandController" type="ARVRController" parent="PlayerOrigin"]
set `controller_id=2` for `RightHandController`

as stated here https://docs.godotengine.org/en/3.1/classes/class_arvrcontroller.html#property-descriptions
```A controller id of 0 is unbound and will always result in an inactive node. Controller id 1 is reserved for the first controller that identifies itself as the left hand controller and id 2 is reserved for the first controller that identifies itself as the right hand controller.```

2019-12-11 13:44 UTC, Girbons commented on Player.tscn
>  transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.85, 0 )
replace `1.85` with `0`

2019-12-11 13:44 UTC, Girbons commented on Player.tscn
> +transform = Transform( -1, 0, -8.74228e-008, 0, 1, 0, 8.74228e-008, 0, -1, 0, 0, 0 )
set `RightHandMesh` rotation to `-148`

2019-12-11 13:44 UTC, Girbons commented on Player.tscn
> +[node name="LeftHandMesh" type="MeshInstance" parent="PlayerOrigin/LeftHandController"]
set `LeftHandMesh` rotation to `148`

2019-12-12 14:00 UTC, ilariacuccaro commented
Fix #6 
Modify HandMesh rotation and ARVRCamera height

2019-12-12 16:58 UTC, MaySantucci approved these changes

2019-12-12 16:59 UTC, merged